<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('diviner', 'atoms/base');


phutil_require_source('DivinerArticleAtom.php');
