<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('diviner', 'parser/docblock');


phutil_require_source('DivinerAtom.php');
