<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('diviner', 'atoms/class');
phutil_require_module('diviner', 'atoms/file');
phutil_require_module('diviner', 'atoms/function');
phutil_require_module('diviner', 'atoms/method');
phutil_require_module('diviner', 'engine/base');

phutil_require_module('phutil', 'filesystem');
phutil_require_module('phutil', 'filesystem/filefinder');
phutil_require_module('phutil', 'future');
phutil_require_module('phutil', 'parser/xhpast/api/tree');
phutil_require_module('phutil', 'parser/xhpast/bin');
phutil_require_module('phutil', 'utils');


phutil_require_source('DivinerXHPEngine.php');
