<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('diviner', 'atoms/article');
phutil_require_module('diviner', 'engine/base');
phutil_require_module('diviner', 'parser/docblock');

phutil_require_module('phutil', 'filesystem');
phutil_require_module('phutil', 'filesystem/filefinder');
phutil_require_module('phutil', 'utils');


phutil_require_source('DivinerArticleEngine.php');
