<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('diviner', 'atoms/base');
phutil_require_module('diviner', 'generator/static');
phutil_require_module('diviner', 'view/article');
phutil_require_module('diviner', 'view/class');
phutil_require_module('diviner', 'view/function');

phutil_require_module('phutil', 'utils');


phutil_require_source('DivinerPublisher.php');
