<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 * @generated
 * @phutil-library-version 2
 */

phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' =>
  array(
    'DivinerArticleAtom' => 'atoms/article/DivinerArticleAtom.php',
    'DivinerArticleAtomView' => 'view/article/DivinerArticleAtomView.php',
    'DivinerArticleEngine' => 'engine/article/DivinerArticleEngine.php',
    'DivinerAtom' => 'atoms/base/DivinerAtom.php',
    'DivinerBaseAtomView' => 'view/base/DivinerBaseAtomView.php',
    'DivinerBaseGenerator' => 'generator/base/DivinerBaseGenerator.php',
    'DivinerClassAtom' => 'atoms/class/DivinerClassAtom.php',
    'DivinerClassAtomView' => 'view/class/DivinerClassAtomView.php',
    'DivinerDefaultRenderer' => 'renderer/default/DivinerDefaultRenderer.php',
    'DivinerEngine' => 'engine/base/DivinerEngine.php',
    'DivinerFileAtom' => 'atoms/file/DivinerFileAtom.php',
    'DivinerFunctionAtom' => 'atoms/function/DivinerFunctionAtom.php',
    'DivinerFunctionAtomView' => 'view/function/DivinerFunctionAtomView.php',
    'DivinerMethodAtom' => 'atoms/method/DivinerMethodAtom.php',
    'DivinerProjectConfiguration' => 'configuration/DivinerProjectConfiguration.php',
    'DivinerPublisher' => 'publisher/DivinerPublisher.php',
    'DivinerRemarkupRuleSymbols' => 'remarkup/symbolrule/DivinerRemarkupRuleSymbols.php',
    'DivinerRenderer' => 'renderer/base/DivinerRenderer.php',
    'DivinerStaticGenerator' => 'generator/static/DivinerStaticGenerator.php',
    'DivinerXHPEngine' => 'engine/xhp/DivinerXHPEngine.php',
  ),
  'function' =>
  array(
  ),
  'xmap' =>
  array(
    'DivinerArticleAtom' => 'DivinerAtom',
    'DivinerArticleAtomView' => 'DivinerBaseAtomView',
    'DivinerArticleEngine' => 'DivinerEngine',
    'DivinerClassAtom' => 'DivinerAtom',
    'DivinerClassAtomView' => 'DivinerBaseAtomView',
    'DivinerDefaultRenderer' => 'DivinerRenderer',
    'DivinerFileAtom' => 'DivinerAtom',
    'DivinerFunctionAtom' => 'DivinerAtom',
    'DivinerFunctionAtomView' => 'DivinerBaseAtomView',
    'DivinerMethodAtom' => 'DivinerAtom',
    'DivinerRemarkupRuleSymbols' => 'PhutilRemarkupRule',
    'DivinerStaticGenerator' => 'DivinerBaseGenerator',
    'DivinerXHPEngine' => 'DivinerEngine',
  ),
));
