<?php

/**
 * This file is automatically generated. Use 'phutil_mapper.php' to rebuild it.
 * @generated
 */

phutil_register_library_map(array(
  'class' =>
  array(
    'DivinerArticleAtom' => 'atoms/article',
    'DivinerArticleAtomView' => 'view/article',
    'DivinerArticleEngine' => 'engine/article',
    'DivinerAtom' => 'atoms/base',
    'DivinerBaseAtomView' => 'view/base',
    'DivinerBaseGenerator' => 'generator/base',
    'DivinerClassAtom' => 'atoms/class',
    'DivinerClassAtomView' => 'view/class',
    'DivinerDefaultRenderer' => 'renderer/default',
    'DivinerEngine' => 'engine/base',
    'DivinerFileAtom' => 'atoms/file',
    'DivinerFunctionAtom' => 'atoms/function',
    'DivinerFunctionAtomView' => 'view/function',
    'DivinerMethodAtom' => 'atoms/method',
    'DivinerProjectConfiguration' => 'configuration',
    'DivinerPublisher' => 'publisher',
    'DivinerRemarkupRuleSymbols' => 'remarkup/symbolrule',
    'DivinerRenderer' => 'renderer/base',
    'DivinerStaticGenerator' => 'generator/static',
    'DivinerXHPEngine' => 'engine/xhp',
  ),
  'function' =>
  array(
  ),
  'requires_class' =>
  array(
    'DivinerArticleAtom' => 'DivinerAtom',
    'DivinerArticleAtomView' => 'DivinerBaseAtomView',
    'DivinerArticleEngine' => 'DivinerEngine',
    'DivinerClassAtom' => 'DivinerAtom',
    'DivinerClassAtomView' => 'DivinerBaseAtomView',
    'DivinerDefaultRenderer' => 'DivinerRenderer',
    'DivinerFileAtom' => 'DivinerAtom',
    'DivinerFunctionAtom' => 'DivinerAtom',
    'DivinerFunctionAtomView' => 'DivinerBaseAtomView',
    'DivinerMethodAtom' => 'DivinerAtom',
    'DivinerRemarkupRuleSymbols' => 'PhutilRemarkupRule',
    'DivinerStaticGenerator' => 'DivinerBaseGenerator',
    'DivinerXHPEngine' => 'DivinerEngine',
  ),
  'requires_interface' =>
  array(
  ),
));
