<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 * @generated
 * @phutil-library-version 2
 */

phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' =>
  array(
    'DivinerArticleAtom' => 'atoms/DivinerArticleAtom.php',
    'DivinerArticleAtomView' => 'view/DivinerArticleAtomView.php',
    'DivinerArticleEngine' => 'engine/DivinerArticleEngine.php',
    'DivinerAtom' => 'atoms/DivinerAtom.php',
    'DivinerBaseAtomView' => 'view/DivinerBaseAtomView.php',
    'DivinerBaseGenerator' => 'generator/DivinerBaseGenerator.php',
    'DivinerClassAtom' => 'atoms/DivinerClassAtom.php',
    'DivinerClassAtomView' => 'view/DivinerClassAtomView.php',
    'DivinerDefaultRenderer' => 'renderer/DivinerDefaultRenderer.php',
    'DivinerEngine' => 'engine/DivinerEngine.php',
    'DivinerFileAtom' => 'atoms/DivinerFileAtom.php',
    'DivinerFunctionAtom' => 'atoms/DivinerFunctionAtom.php',
    'DivinerFunctionAtomView' => 'view/DivinerFunctionAtomView.php',
    'DivinerInterfaceAtom' => 'atoms/DivinerInterfaceAtom.php',
    'DivinerMethodAtom' => 'atoms/DivinerMethodAtom.php',
    'DivinerProjectConfiguration' => 'configuration/DivinerProjectConfiguration.php',
    'DivinerPublisher' => 'publisher/DivinerPublisher.php',
    'DivinerRemarkupRuleSymbols' => 'remarkup/DivinerRemarkupRuleSymbols.php',
    'DivinerRenderer' => 'renderer/DivinerRenderer.php',
    'DivinerStaticGenerator' => 'generator/DivinerStaticGenerator.php',
    'DivinerXHPEngine' => 'engine/DivinerXHPEngine.php',
  ),
  'function' =>
  array(
  ),
  'xmap' =>
  array(
    'DivinerArticleAtom' => 'DivinerAtom',
    'DivinerArticleAtomView' => 'DivinerBaseAtomView',
    'DivinerArticleEngine' => 'DivinerEngine',
    'DivinerClassAtom' => 'DivinerAtom',
    'DivinerClassAtomView' => 'DivinerBaseAtomView',
    'DivinerDefaultRenderer' => 'DivinerRenderer',
    'DivinerFileAtom' => 'DivinerAtom',
    'DivinerFunctionAtom' => 'DivinerAtom',
    'DivinerFunctionAtomView' => 'DivinerBaseAtomView',
    'DivinerInterfaceAtom' => 'DivinerClassAtom',
    'DivinerMethodAtom' => 'DivinerAtom',
    'DivinerRemarkupRuleSymbols' => 'PhutilRemarkupRule',
    'DivinerStaticGenerator' => 'DivinerBaseGenerator',
    'DivinerXHPEngine' => 'DivinerEngine',
  ),
));
