<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('diviner', 'generator/base');
phutil_require_module('diviner', 'renderer/default');

phutil_require_module('phutil', 'filesystem');
phutil_require_module('phutil', 'markup');
phutil_require_module('phutil', 'moduleutils');
phutil_require_module('phutil', 'utils');


phutil_require_source('DivinerStaticGenerator.php');
