<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('diviner', 'view/base');

phutil_require_module('phutil', 'markup');


phutil_require_source('DivinerFunctionAtomView.php');
